version: '2.1'
services: 
  config-server:
    container_name: config-server
    build: ./agenda-config-server
    restart: on-failure
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/agenda-eureka-server/default"]
      interval: 45s
      timeout: 5s
      retries: 60
  
  eureka-server:
    container_name: eureka-server
    build: ./agenda-eureka-server
    restart: on-failure
    ports:
      - "9091:9091"
    depends_on:
      config-server:
        condition: service_healthy
    links:
      - config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091"]
      interval: 60s
      timeout: 5s
      retries: 60

  agenda-cadastro:
    container_name: agenda-cadastro
    restart: on-failure
    build: ./agenda-cadastro-server
    ports:
      - "9092:9092"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    links:
      - config-server
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092/api/v1/contatos"]
      interval: 60s
      timeout: 5s
      retries: 60
    
  gateway-server:
    container_name: gateway-server
    restart: on-failure
    build: ./agenda-gateway-server
    ports:
      - "9094:9094"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      agenda-cadastro:
        condition: service_healthy
    links:
      - config-server
      - eureka-server
      - agenda-cadastro